sudo: require
services:
  - docker

before_install:
  - docker build -t aleskotnik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aleskotnik/react-test npm test -- --coverage

after_success:
  - docker build -t aleskotnik/multi-client ./clinet --no-cache
  - docker build -t aleskotnik/multi-server ./server --no-cache
  - docker build -t aleskotnik/multi-worker ./worker --no-cache
  - docker build -t aleskotnik/multi-nginx ./nginx --no-cache

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push aleskotnik/multi-client
  - docker push aleskotnik/multi-server
  - docker push aleskotnik/multi-worker
  - docker push aleskotnik/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-787424217056
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

