version: "3"
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    image: 'aleskotnik/multi-server'
    volumes:
      - /app/node_modules # don't overrider node_modules inside container
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379      
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    image: 'aleskotnik/multi-client'
    volumes:
      - /app/node_modules # don't overrider node_modules inside container
      - ./client:/app
  worker:
    image: 'aleskotnik/multi-worker'
    volumes:
      - /app/node_modules # don't overrider node_modules inside container
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    image: 'aleskotnik/multi-nginx'
    ports:
      - '3050:80'

